// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADjBQPpnFhRxLNfcrbe5UQ-Uwv6zfKaXQ',
    appId: '1:984067254152:web:536cc4f58a937423bcbc3d',
    messagingSenderId: '984067254152',
    projectId: 'phuong-7fa75',
    authDomain: 'phuong-7fa75.firebaseapp.com',
    storageBucket: 'phuong-7fa75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS2C0KuMEq2dBiipcvM95fSq3nwTTL9fM',
    appId: '1:984067254152:android:398aafc0edcaa1f4bcbc3d',
    messagingSenderId: '984067254152',
    projectId: 'phuong-7fa75',
    storageBucket: 'phuong-7fa75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZ9-AlVfX5oYmVThso41qgAiYZBlG3ew',
    appId: '1:984067254152:ios:7296b7b7b8079c5cbcbc3d',
    messagingSenderId: '984067254152',
    projectId: 'phuong-7fa75',
    storageBucket: 'phuong-7fa75.appspot.com',
    iosBundleId: 'com.example.phuong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZ9-AlVfX5oYmVThso41qgAiYZBlG3ew',
    appId: '1:984067254152:ios:7296b7b7b8079c5cbcbc3d',
    messagingSenderId: '984067254152',
    projectId: 'phuong-7fa75',
    storageBucket: 'phuong-7fa75.appspot.com',
    iosBundleId: 'com.example.phuong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADjBQPpnFhRxLNfcrbe5UQ-Uwv6zfKaXQ',
    appId: '1:984067254152:web:29c391348fb0f8f7bcbc3d',
    messagingSenderId: '984067254152',
    projectId: 'phuong-7fa75',
    authDomain: 'phuong-7fa75.firebaseapp.com',
    storageBucket: 'phuong-7fa75.appspot.com',
  );
}
